/**
 * Skill File Generator
 *
 * Generates per-community skill/context files from the knowledge graph.
 * No LLM required — purely graph-derived. Output lands in
 * .claude/skills/codemind/ by default, making communities directly
 * discoverable by Claude Code as persistent context.
 */

import * as fs from 'fs';
import * as path from 'path';
import type { SqliteDatabase } from '../db/sqlite-adapter';
import { validatePathWithinRoot } from '../utils';

interface CommunityRow {
  community_id: string;
  community_name: string;
  cnt: number;
}

interface NodeRow {
  node_id: string;
  name: string;
  kind: string;
  file_path: string;
  start_line: number;
  signature: string | null;
  docstring: string | null;
}

interface FlowRow {
  entry_node_id: string;
  flow_json: string;
  node_count: number;
}

const MIN_COMMUNITY_SIZE = 5;

export interface SkillGenerationResult {
  generated: string[];
  skipped: number;
}

/**
 * Generate one Markdown skill file per community in the graph.
 *
 * @param db - Raw SQLite database handle
 * @param projectRoot - Absolute path to the project root (used for default output dir)
 * @param outputDir - Override destination directory (default: .claude/skills/codemind/)
 * @returns Paths of generated files and count of skipped communities
 *
 * Time Complexity: O(C × N) where C = community count, N = avg members per community
 * Space Complexity: O(N) per community (not accumulated)
 */
export function generateSkillFiles(
  db: SqliteDatabase,
  projectRoot: string,
  outputDir?: string,
): SkillGenerationResult {
  const defaultDir = path.join(projectRoot, '.claude', 'skills', 'codemind');
  const skillsDir = outputDir ?? defaultDir;

  // Reject paths that escape the project root when an override is supplied
  if (outputDir) {
    const safe = validatePathWithinRoot(projectRoot, outputDir);
    if (!safe) {
      throw new Error(`outputDir "${outputDir}" is outside the project root "${projectRoot}"`);
    }
  }

  fs.mkdirSync(skillsDir, { recursive: true });

  // Get top communities by member count, skipping tiny ones
  const communities = db.prepare(`
    SELECT community_id, community_name, COUNT(*) as cnt
    FROM node_communities
    GROUP BY community_id
    HAVING cnt >= ?
    ORDER BY cnt DESC
    LIMIT 50
  `).all(MIN_COMMUNITY_SIZE) as CommunityRow[];

  if (communities.length === 0) {
    return { generated: [], skipped: 0 };
  }

  const generated: string[] = [];
  let skipped = 0;

  for (const community of communities) {
    // Get key nodes for this community — only actionable kinds
    const nodes = db.prepare(`
      SELECT nc.node_id, n.name, n.kind, n.file_path, n.start_line, n.signature, n.docstring
      FROM node_communities nc JOIN nodes n ON nc.node_id = n.id
      WHERE nc.community_id = ?
        AND n.kind IN ('function', 'method', 'class', 'interface', 'struct', 'route', 'component')
      ORDER BY n.kind, n.name
    `).all(community.community_id) as NodeRow[];

    if (nodes.length === 0) {
      skipped++;
      continue;
    }

    // Get entry points in this community from precomputed execution_flows
    const flows = db.prepare(`
      SELECT ef.entry_node_id, ef.flow_json, ef.node_count
      FROM execution_flows ef
      JOIN node_communities nc ON ef.entry_node_id = nc.node_id
      WHERE nc.community_id = ?
      ORDER BY ef.node_count DESC
      LIMIT 3
    `).all(community.community_id) as FlowRow[];

    // Unique files — cap to 10 for readability
    const files = [...new Set(nodes.map(n => n.file_path))].slice(0, 10);

    const skillName = community.community_name.replace(/[^a-zA-Z0-9-_]/g, '-');
    const filePath = path.join(skillsDir, `${skillName}.md`);

    const lines: string[] = [
      `# ${community.community_name} module`,
      '',
      `> Auto-generated by \`codemind skills generate\` — ${new Date().toISOString().split('T')[0]}`,
      `> ${nodes.length} symbols across ${files.length} file(s).`,
      '',
      '## Key files',
      '',
      ...files.map(f => `- \`${f}\``),
      '',
    ];

    // Entry points section
    if (flows.length > 0) {
      lines.push('## Entry points');
      lines.push('');
      for (const flow of flows) {
        let steps: Array<{ name: string; kind: string; filePath: string; line: number }>;
        try {
          steps = JSON.parse(flow.flow_json) as typeof steps;
        } catch {
          continue;
        }
        const entry = steps[0];
        if (entry) {
          lines.push(`- \`${entry.name}\` (${entry.kind}) — \`${entry.filePath}:${entry.line}\``);
          if (steps.length > 1) {
            const chain = steps.slice(1, 4).map(s => s.name).join(' → ');
            const suffix = steps.length > 4 ? ' ...' : '';
            lines.push(`  - calls: ${chain}${suffix}`);
          }
        }
      }
      lines.push('');
    }

    // Key symbols grouped by kind
    const byKind = new Map<string, NodeRow[]>();
    for (const node of nodes) {
      const group = byKind.get(node.kind) ?? [];
      group.push(node);
      byKind.set(node.kind, group);
    }

    for (const [kind, kindNodes] of byKind) {
      const heading = kind.charAt(0).toUpperCase() + kind.slice(1) + 's';
      lines.push(`## ${heading}`);
      lines.push('');
      for (const node of kindNodes.slice(0, 15)) {
        let line = `- \`${node.name}\` — \`${node.file_path}:${node.start_line}\``;
        if (node.signature) line += `\n  \`${node.signature}\``;
        if (node.docstring && node.docstring.length < 120) line += `\n  ${node.docstring}`;
        lines.push(line);
      }
      if (kindNodes.length > 15) lines.push(`- ... and ${kindNodes.length - 15} more`);
      lines.push('');
    }

    lines.push('---');
    lines.push('');
    lines.push('Use `codemind_clusters` or `codemind_explore` to get more context about this module.');

    fs.writeFileSync(filePath, lines.join('\n'), 'utf-8');
    generated.push(filePath);
  }

  return { generated, skipped };
}
